spring:
  datasource:
    #remote server
    url: jdbc:postgresql://91.107.126.163:5433/flat_rent
    username: postgres
    password: postgres
    driver: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    logging:
      level:
        org:
          hibernate:
            orm:
              jdbc:
                bind: TRACE